In [1]:
import pandas as pd
import numpy as np

df_raw = pd.read_csv("InputFiles/hotel_bookings.csv")
df_raw.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [2]:
df_Copy = df_raw.copy()
df_Copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [3]:
df_Copy.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [4]:
df_Copy["reservation_status_date"] = pd.to_datetime(df_Copy["reservation_status_date"])
df_Copy = df_Copy.sort_values('reservation_status_date').reset_index(drop=True)
df_Copy.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,City Hotel,1,300,2015,August,33,13,0,2,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.8,0,0,Canceled,2014-10-17
1,City Hotel,1,286,2015,July,31,30,0,2,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.8,0,0,Canceled,2014-10-17
2,City Hotel,1,286,2015,July,31,30,0,2,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.8,0,0,Canceled,2014-10-17
3,City Hotel,1,286,2015,July,31,30,0,2,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.8,0,0,Canceled,2014-10-17
4,City Hotel,1,286,2015,July,31,30,0,2,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.8,0,0,Canceled,2014-10-17

In [5]:
# types_of_status = df_Copy["reservation_status"].unique()
reservation_status_withoutCanceled = df_Copy[df_Copy["reservation_status"] == "Check-Out"].copy()
print(f"Total rows: {len(reservation_status_withoutCanceled)}")
print(f"Shape: {reservation_status_withoutCanceled.shape}")
print(f"Rows: {reservation_status_withoutCanceled.shape[0]}")
print(f"Columns: {reservation_status_withoutCanceled.shape[1]}")
print(f"Total elements: {reservation_status_withoutCanceled.size}")

Total rows: 75166
Shape: (75166, 32)
Rows: 75166
Columns: 32
Total elements: 2405312

In [6]:
reservation_status_withoutCanceled["Total_nights"] = reservation_status_withoutCanceled["stays_in_weekend_nights"] + reservation_status_withoutCanceled["stays_in_week_nights"]
reservation_status_withoutCanceled.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,Total_nights
2355,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,0
2357,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,0
2362,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,115.0,NaN,0,Contract,94.95,0,1,Check-Out,2015-07-01,7
2435,Resort Hotel,0,4,2015,July,27,1,0,1,1,...,NaN,204.0,0,Transient,134.00,0,0,Check-Out,2015-07-02,1
2438,Resort Hotel,0,2,2015,July,27,1,0,1,1,...,240.0,NaN,0,Transient,4.00,0,1,Check-Out,2015-07-02,1

In [7]:
month_stays = (reservation_status_withoutCanceled
               .groupby("arrival_date_month")
               .agg(Total_stays=("arrival_date_month","size"),
                    Total_nights=("Total_nights",sum),
                    average_price=("adr","mean"))
               .reset_index())
month_stays["average_price"] = month_stays["average_price"].round(2)

/var/folders/wr/w1_zrsw175n749bp4qzldbw00000gn/T/ipykernel_2362/390611855.py:3: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  .agg(Total_stays=("arrival_date_month","size"),

In [8]:
month_stays.head(12)

   arrival_date_month  Total_stays  Total_nights  average_price
0               April         6565         21795          97.88
1              August         8638         33789         142.09
2            December         4409         13324          78.92
3            February         5372         15788          72.42
4             January         4122         11332          67.00
5                July         7919         30912         129.25
6                June         6404         23146         114.59
7               March         6645         21811          77.33
8                 May         7114         23616         104.84
9            November         4672         14735          70.51
10            October         6914         21834          86.83
11          September         6392         22958         107.28

In [9]:
month_order = ["January","February","March","April","May","June","July","August","September","October","November","December"]
month_stays["arrival_date_month"] = pd.Categorical(month_stays["arrival_date_month"],categories=month_order,ordered=True)
month_stays = month_stays.sort_values("arrival_date_month")

In [ ]:
month_stays.head(12)

   arrival_date_month  Total_stays  Total_nights  average_price
4             January         4122         11332          67.00
3            February         5372         15788          72.42
7               March         6645         21811          77.33
0               April         6565         21795          97.88
8                 May         7114         23616         104.84
6                June         6404         23146         114.59
5                July         7919         30912         129.25
1              August         8638         33789         142.09
11          September         6392         22958         107.28
10            October         6914         21834          86.83
9            November         4672         14735          70.51
2            December         4409         13324          78.92

In [11]:
new_dataSet = month_stays["total_stays"].sum()
print(new_dataSet)

KeyError: 'total_stays'